apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plextraktsync.fullname" . }}-config
data:
  config.yml: |
    plex:
      url: {{ .Values.plex.url }}
    sync_interval: {{ .Values.syncInterval }}