apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plextraktsync.fullname" . }}-config-pvc
  labels:
    {{- include "plextraktsync.labels" . | nindent 4 }}
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 2 }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}