apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unserneuesheim-https
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unserneuesheim.de`)
      kind: Rule
      services:
        - name: unserneuesheim-service
          port: 80
      middlewares:
        - name: traefik-default-headers@kubernetescrd
    - match: Host(`www.unserneuesheim.de`)
      kind: Rule
      services:
        - name: unserneuesheim-service
          port: 80
      middlewares:
        - name: traefik-default-headers@kubernetescrd
---
apiVersion: v1
kind: Service
metadata:
  name: unserneuesheim-service
  namespace: traefik
spec:
  type: ExternalName
  externalName: 192.168.0.201  # Target backend IP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http