apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}
    app.kubernetes.io/name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        app.kubernetes.io/instance: {{ .Values.appName }}
        app.kubernetes.io/name: {{ .Values.appName }}
    spec:
      nodeSelector:
        worker: "true"
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image }}
        env:
        - name: GOTIFY_DB_SQLITE
          value: /app/data/gotify.db
        - name: GOTIFY_PORT
          value: "80"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: {{ .Values.appName }}
          mountPath: /app/data
      volumes:
      - name: {{ .Values.appName }}
        persistentVolumeClaim:
          claimName: {{ .Values.appName }}