---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.appName }}
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.{{ .Values.appName }}.{{ .Values.domain }}.de`) # change to your domain
      kind: Rule
      services:
        - name: {{ .Values.appName }}
          port: 80
      middlewares:
        - name: traefik-default-headers@kubernetescrd
    - match: Host(`{{ .Values.appName }}.{{ .Values.domain }}.de`) # change to your domain
      kind: Rule
      services:
        - name: {{ .Values.appName }}
          port: 80
      middlewares:
        - name: traefik-default-headers@kubernetescrd
  # tls:
  #   secretName: {{ .Values.domain }}-tls # change to your cert
