---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.{{ .Values.appName }}.unserneuesheim.de`) # change to your domain
      kind: Rule
      services:
        - name: {{ .Values.appName }}
          port: 80
    - match: Host(`gotify.unserneuesheim.de`) # change to your domain
      kind: Rule
      services:
        - name: {{ .Values.appName }}
          port: 80
      middlewares:
        - name: default-headers
  tls:
    secretName: unserneuesheim-tls # change to your cert
