# Copy and rename this file as necessary
---
apiVersion: v1
kind: Secret
metadata:
  name: filebot-license
  namespace: filebot
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:    
    meta.helm.sh/release-name: "filebot"
    meta.helm.sh/release-namespace: "filebot"
type: Opaque
data:
  license.psm: <REPLACE WITH YOUR LICENSE BASE64 ENCODED> # this is a base64 encoded string. Create using echo -n 'super-secret-password' | base64