apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ default "80" .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "app-chart.selectorLabels" . | nindent 4 }}
