# Attention: This is currently not working since I could not manage truecharts to 
# reference an existing secret.

# Copy this template and save it to ~/Helm/plextraktsync/plextraktsync-secret.yaml. 
# Change the settings as you need to.
# Then apply it using kubectl apply -f ~/Helm/plextraktsync/plextraktsync-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: plextraktsync-secret
  namespace: plextraktsync # Replace with the namespace where the Certificate resides
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:    
    meta.helm.sh/release-name: "plextraktsync"
    meta.helm.sh/release-namespace: "plextraktsync"
type: Opaque
stringData:
  .env: |
    # This is .env file for PlexTraktSync
    PLEX_USERNAME=<YOUR PLEX USERNAME>
    TRAKT_USERNAME=<YOUR PLEX EMAIL>
    PLEX_SERVER=<YOUR PLEX SERVERNAME>
    PLEX_OWNER_TOKEN=<YOUR PLEX OWNER TOKEN>
    PLEX_ACCOUNT_TOKEN=

  servers.yml: |
    servers:
      default:
        token: null
        urls:
        - null
        - null
        id: null
        config: null
      <YOUR PLEX SERVERNAME>:
        token: <YOUR PLEX TOKEN>
        urls:
        - <URL1>
        - <URL2>
        - ...
        id: <SOME ID>
        config: null

  .pytrakt.json: |
    {"APPLICATION_ID": null, "CLIENT_ID": "<YOUR TRAKT CLIENT ID>", "CLIENT_SECRET": "<YOUR TRAKT CLIENT SECRET>", "OAUTH_EXPIRES_AT": 1753010211, "OAUTH_REFRESH": "<YOUR TRAKT REFRESH INFO>", "OAUTH_TOKEN": "<YOUR TRAKT TOKEN>"}