---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.plex.unserneuesheim.de`) # change to your domain
      kind: Rule
      services:
        - name: plex-media-server
          port: 32400
    - match: Host(`plex.unserneuesheim.de`) # change to your domain
      kind: Rule
      services:
        - name: plex-media-server
          port: 32400
      middlewares:
        - name: default-headers
  tls:
    secretName: unserneuesheim-tls # change to your cert
