# Copy and rename this file as necessary
---
apiVersion: v1
kind: Secret
metadata:
  name: inwx-credentials
  namespace: cert-manager
type: Opaque
stringData:
  username: <YOUR USERNAME>
  password: <YOUR PASSWORD>
  otpKey: <YOUR OTP TOKEN>