apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ionos-production
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: <YOUR EMAIL> # add your email
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-ionos-production
    # Enable the dns01 challenge provider
    solvers:
      - dns01:
          webhook:
            groupName: acme.<YOUR COMPANY NAME.de>
            solverName: ionos
            config:
              apiUrl: https://api.hosting.ionos.com/dns/v1
              publicKeySecretRef:
                key: IONOS_PUBLIC_PREFIX
                name: cert-manager-webhook-ionos
              secretKeySecretRef:
                key: IONOS_SECRET
                name: cert-manager-webhook-ionos
        selector:
          dnsZones:
            - "<YOUR DOMAIN 1>"
            - "<YOUR DOMAIN 2>"
            - "<YOUR DOMAIN 3>"