{{- if and .Values.persistence.enabled (eq .Values.persistence.existingClaim "") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "firefly-iii-fints-importer.fullname" . }}
  labels:
    {{- include "firefly-iii-fints-importer.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
{{- end }}