{{- if .Values.initContainer.script -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "chart.fullname" . }}-init-script
  labels:
{{- include "chart.labels" . | nindent 4 }}
data:
  init.sh: |
{{ .Values.initContainer.script | indent 4 }}
{{- end -}}
