apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "app-chart.fullname" . }}-profiles
  labels:
{{- include "app-chart.labels" . | nindent 4 }}
data:
  Custom.mmcp.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <profile>
        <!-- profile name - Custom -->
        <name lang="mogz">Custom</name>

        <!-- Common MKV flags -->
        <mkvSettings 
            ignoreForcedSubtitlesFlag="false"
            useISO639Type2T="false"
            setFirstAudioTrackAsDefault="true"
            setFirstSubtitleTrackAsDefault="true"
            setFirstForcedSubtitleTrackAsDefault="true"
            insertFirstChapter00IfMissing="true"
        />

        <!-- This tag is ignored by MakeMKV 1.12.4 and later, do not change it here. Set the app_DefaultSelectionString
            value in preferences. Keep this element in your custom profiles only for compatibility with older MakeMKV versions.
        -->
        <profileSettings
            app_DefaultSelectionString="-sel:all,+sel:(favlang|eng|nolang|single),-sel:(havemulti),-sel:(multi*(~core)),-sel:mvcvideo,=100:all,-10:favlang"
        />

        <!-- Output formats currently supported by MakeMKV -->
        <outputSettings name="copy" outputFormat="directCopy">
            <description lang="eng">Copy track as is</description>
        </outputSettings>

        <outputSettings name="lpcm" outputFormat="LPCM-raw">
            <description lang="eng">Save as raw LPCM</description>
        </outputSettings>

        <outputSettings name="wavex" outputFormat="LPCM-wavex">
            <description lang="eng">Save as LPCM in WAV container</description>
        </outputSettings>

        <outputSettings name="flac-best" outputFormat="FLAC">
            <description lang="eng">Save as FLAC (best compression)</description>
            <extraArgs>-compression_level 12</extraArgs>
        </outputSettings>

        <outputSettings name="flac-fast" outputFormat="FLAC">
            <description lang="eng">Save as FLAC (fast compression)</description>
            <extraArgs>-compression_level 5</extraArgs>
        </outputSettings>

        <!-- Default rule - copy as is -->
        <trackSettings input="default">
            <output outputSettingsName="copy" 
                    defaultSelection="$app_DefaultSelectionString">
            </output>
        </trackSettings>

        <!-- Save LPCM mono or stereo as raw LPCM -->
        <trackSettings input="LPCM-stereo">
            <output outputSettingsName="lpcm"
                    defaultSelection="$app_DefaultSelectionString">
            </output>
        </trackSettings>

        <!-- Put multi-channel LPCM into WAVEX container-->
        <trackSettings input="LPCM-multi">
            <output outputSettingsName="wavex"
                    defaultSelection="$app_DefaultSelectionString">
            </output>
        </trackSettings>

        <!-- Custom Rule: Copy DTS-HD in container and convert to flac-->
        <!-- Uncomment for 4K UHD Blu-rays -->
        <trackSettings input="DTSHDMA-multi">
            <output outputSettingsName="flac-best"
                    defaultSelection="$app_DefaultSelectionString,-10:true">   
            </output>
        </trackSettings>
        

        <!-- Custom Rule: Copy TRUE-HD in container and convert to flac-->
        <!-- Uncomment for 4K UHD Blu-rays -->
        <trackSettings input="TRUEHD-multi">
            <output outputSettingsName="flac-best"
                    defaultSelection="$app_DefaultSelectionString,-10:true">
            </output>
        </trackSettings>

        <!-- Convert closed captions to text subtitles
            This rule is added automatically by default if no 
            other <trackSettings input="CC"> tags are present.
            Uncomment to override as needed. -->
        <!--
        <outputSettings name="convertToSRT" outputFormat="SRT">
            <description lang="eng">Convert to text subtitles</description>
        </outputSettings>
        <trackSettings input="CC">
            <output outputSettingsName="convertToSRT"
                    defaultSelection="$app_DefaultSelectionString">
            </output>
        </trackSettings>
        -->

    </profile>