# Copy and rename this file as necessary
---
apiVersion: v1
kind: Secret
metadata:
  name: makemkv-license
  namespace: makemkv # Replace with the namespace where the Certificate resides
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:    
    meta.helm.sh/release-name: "makemkv"
    meta.helm.sh/release-namespace: "makemkv"
type: Opaque
data:
  MAKEMKV_KEY: <REPLACE WITH YOUR LICENSE BASE64 ENCODED> # this is a base64 encoded string. Create using echo -n 'super-secret-password' | base64