apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-dvddrive
spec:
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      groupRecursive: true # Recommended unless using very exact udev rules
      udevRules:
      - ATTRS{idVendor}=="1e91", ATTRS{idProduct}=="de2c"
    name: udev